<?php
/**
 * English (United Kingdom)
 */

return [
    '_meta' => [
        'nazwa'    => 'English',
        'ikona'    => '🇬🇧',
        'kierunek' => 'ltr',
        'kod_html' => 'en-GB',
    ],

    'strona' => [
        'tytul'        => 'Dream Film — AI Generator',
        'opis'         => 'Transform your dream into a short film using artificial intelligence. Screenplay, images, video, narration, and music — all created by AI.',
        'slowa_klucze' => 'AI, film, dream, generator, artificial intelligence, Pollinations',
    ],

    'naglowek' => [
        'tytul'    => '🎬 Dream Film',
        'podtytul' => 'Turn your dream into an AI cinematic masterpiece',
    ],

    'menu' => [
        'strona_glowna' => 'Home',
        'jak_dziala'    => 'How it works',
        'sny'           => 'Dreams',
        'wszystkie_sny' => 'All Dreams',
        'jezyk'         => 'Language',
    ],

    'formularz' => [
        'tytul'         => 'Describe your dream',
        'placeholder'   => 'Close your eyes and recall your dream... Describe it in as much detail as possible: what did you see, hear, feel? What colours, places, and characters appeared?',
        'lub'           => 'or',
        'nagraj_sen'    => '🎙️ Record your dream',
        'nagrywanie'    => '⏹️ Stop recording',
        'typ_glosu'     => 'Narration type',
        'glos_meski'    => '🎭 Male narrator',
        'glos_zenski'   => '🎭 Female narrator',
        'glos_tajemny'  => '🌙 Mysterious voice',
        'generuj_wideo' => 'Also generate video clips',
        'stworz'        => '✨ Create a film from my dream',
        'wymagane'      => 'Describe your dream — at least 20 characters',
    ],

    'postep' => [
        'tytul'        => 'Creating your film...',
        'inicjalizacja' => '🎬 Initialising project...',
        'scenariusz'   => '📝 AI is writing the screenplay...',
        'obraz'        => '🖼️ Generating image for scene {numer}...',
        'narracja'     => '🎤 Recording narration for scene {numer}...',
        'muzyka'       => '🎵 Composing music for scene {numer}...',
        'wideo'        => '🎬 Rendering video for scene {numer}...',
        'zapisz'       => '💾 Saving dream to archive...',
        'gotowe'       => '✅ Film is ready!',
        'blad'         => '❌ An error occurred: {komunikat}',
        'cierpliwosci' => 'This may take a few minutes — AI is creating a work of art...',
    ],

    'sceny' => [
        'scena'            => 'Scene {numer}',
        'model_obrazu'     => 'Image model',
        'model_wideo'      => 'Video model',
        'glos'             => 'Voice',
        'odtworz_narracje' => '▶️ Narration',
        'odtworz_muzyke'   => '🎵 Music',
        'odtworz_wideo'    => '🎬 Video',
    ],

    'odtwarzacz' => [
        'tytul'      => 'Film player',
        'odtworz'    => '▶️ Play all',
        'pauza'      => '⏸️ Pause',
        'nastepna'   => '⏭️ Next scene',
        'poprzednia' => '⏮️ Previous scene',
        'pelny_ekran' => '🔳 Full screen',
    ],

    'informacje' => [
        'tytul_filmu' => 'Title',
        'gatunek'     => 'Genre',
        'nastroj'     => 'Mood',
        'modele'      => 'AI models used',
        'id_projektu' => 'Project ID',
        'link_snu'    => '🌙 View this dream publicly',
    ],

    'sny' => [
        'tytul_strony'       => 'Dreams',
        'opis_strony'        => 'Browse AI-generated dreams — each dream is a unique work of imagination.',
        'wszystkie_tytul'    => 'All Dreams',
        'wszystkie_opis'     => 'Dreams from all languages — discover the oneiric worlds of others.',
        'filtr_dzien'        => 'Dreams from {dzien} {miesiac} {rok}',
        'filtr_miesiac'      => 'Dreams from {miesiac} {rok}',
        'filtr_rok'          => 'Dreams from {rok}',
        'brak_snow'          => 'No dreams found in this period.',
        'brak_snow_jezyk'    => 'No dreams in this language for the selected period.',
        'brak_snow_wszystkie' => 'No dreams in the archive yet.',
        'zobacz_sen'         => 'View Dream',
        'powrot'             => '← Back to dreams',
        'odtworz_film'       => '▶ Play film',
        'strona'             => 'Page',
        'z'                  => 'of',
        'poprzednia'         => '← Previous',
        'nastepna'           => 'Next →',
        'wstep'              => 'Dream introduction',
        'gatunek'            => 'Genre',
        'nastroj'            => 'Mood',
        'data_snu'           => 'Dream date',
        'jezyk_snu'          => 'Original language',
        'archiwum'           => 'Archive',
        'sen_zapisany'       => '✅ Dream saved to archive!',
        'sen_link'           => 'View it here',
        'miesiac_01'         => 'January',
        'miesiac_02'         => 'February',
        'miesiac_03'         => 'March',
        'miesiac_04'         => 'April',
        'miesiac_05'         => 'May',
        'miesiac_06'         => 'June',
        'miesiac_07'         => 'July',
        'miesiac_08'         => 'August',
        'miesiac_09'         => 'September',
        'miesiac_10'         => 'October',
        'miesiac_11'         => 'November',
        'miesiac_12'         => 'December',
    ],

    'jak_dziala' => [
        'tytul'             => 'How does it work?',
        'opis'              => 'Dream Film is an AI app that turns your dream description into a real cinematic experience.',
        'krok_1_tytul'      => '1. Describe your dream',
        'krok_1_opis'       => 'Type your dream description — the more detail, the more beautiful the film. You can also record your description by voice.',
        'krok_2_tytul'      => '2. AI writes the screenplay',
        'krok_2_opis'       => 'Artificial intelligence analyses your dream and creates a 4-scene film screenplay with title, genre, and mood.',
        'krok_3_tytul'      => '3. Image generation',
        'krok_3_opis'       => 'Each scene receives a unique AI image — surreal, cinematic, matching the dream\'s mood.',
        'krok_4_tytul'      => '4. Narration and music',
        'krok_4_opis'       => 'AI records voice narration for each scene and composes background music tailored to the atmosphere.',
        'krok_5_tytul'      => '5. Optional video',
        'krok_5_opis'       => 'You can generate animated video clips for each scene to bring your dream to life.',
        'krok_6_tytul'      => '6. Watch and share',
        'krok_6_opis'       => 'Watch the finished film in the player, and your dream is added to the public dream archive.',
        'technologie_tytul' => 'Technologies',
        'technologie_opis'  => 'The application uses Pollinations AI — a free platform with access to many AI models.',
        'faq_tytul'         => 'Frequently asked questions',
        'faq_1_pytanie'     => 'Is it free?',
        'faq_1_odpowiedz'   => 'Yes! The application uses free Pollinations AI models. Only an API key is required.',
        'faq_2_pytanie'     => 'How long does generation take?',
        'faq_2_odpowiedz'   => 'Usually 1–3 minutes without video, 5–10 minutes with video.',
        'faq_3_pytanie'     => 'What languages are supported?',
        'faq_3_odpowiedz'   => 'The screenplay and narration are generated in the language chosen by the user.',
    ],

    'stopka' => [
        'tekst'       => 'Created with Pollinations AI',
        'prawa'       => '© {rok} Dream Film. All rights reserved.',
        'technologie' => 'Technologies',
    ],

    'bledy' => [
        'brak_opisu'     => 'Please enter a dream description.',
        'za_krotki'      => 'Dream description is too short — minimum 20 characters.',
        'blad_serwera'   => 'Server error. Please try again later.',
        'blad_api'       => 'AI communication error. Please check the API key.',
        'brak_mikrofonu' => 'Microphone access denied.',
        'nie_znaleziono' => 'Dream not found.',
        'blad_404'       => 'Page not found.',
    ],
];
