<?php
/**
 * Polski — jezyk glowny
 */

return [
    '_meta' => [
        'nazwa'    => 'Polski',
        'ikona'    => '🇵🇱',
        'kierunek' => 'ltr',
        'kod_html' => 'pl',
    ],

    'strona' => [
        'tytul'        => 'Film ze Snu — Generator AI',
        'opis'         => 'Zamien swoj sen w krotki film przy pomocy sztucznej inteligencji. Scenariusz, obrazy, wideo, narracja i muzyka — wszystko tworzone przez AI.',
        'slowa_klucze' => 'AI, film, sen, generator, sztuczna inteligencja, Pollinations',
    ],

    'naglowek' => [
        'tytul'    => '🎬 Film ze Snu',
        'podtytul' => 'Zamien swoj sen w dzielo filmowe AI',
    ],

    'menu' => [
        'strona_glowna' => 'Strona glowna',
        'jak_dziala'    => 'Jak to dziala?',
        'sny'           => 'Sny',
        'wszystkie_sny' => 'Wszystkie Sny',
        'jezyk'         => 'Jezyk',
    ],

    'formularz' => [
        'tytul'         => 'Opisz swoj sen',
        'placeholder'   => 'Zamknij oczy i przypomnij sobie swoj sen... Opisz go jak najdokladniej: co widziales, slyszales, czules? Jakie kolory, miejsca, postacie sie pojawily?',
        'lub'           => 'lub',
        'nagraj_sen'    => '🎙️ Nagraj opis snu',
        'nagrywanie'    => '⏹️ Zatrzymaj nagrywanie',
        'typ_glosu'     => 'Typ narracji',
        'glos_meski'    => '🎭 Meski narrator',
        'glos_zenski'   => '🎭 Zenski narrator',
        'glos_tajemny'  => '🌙 Tajemniczy glos',
        'generuj_wideo' => 'Generuj rowniez klipy wideo',
        'stworz'        => '✨ Stworz film z mojego snu',
        'wymagane'      => 'Opisz swoj sen — minimum 20 znakow',
    ],

    'postep' => [
        'tytul'        => 'Tworzenie filmu...',
        'inicjalizacja' => '🎬 Inicjalizacja projektu...',
        'scenariusz'   => '📝 AI pisze scenariusz...',
        'obraz'        => '🖼️ Generowanie obrazu sceny {numer}...',
        'narracja'     => '🎤 Nagrywanie narracji sceny {numer}...',
        'muzyka'       => '🎵 Kompozycja muzyki sceny {numer}...',
        'wideo'        => '🎬 Renderowanie wideo sceny {numer}...',
        'zapisz'       => '💾 Zapisywanie snu w archiwum...',
        'gotowe'       => '✅ Film gotowy!',
        'blad'         => '❌ Wystapil blad: {komunikat}',
        'cierpliwosci' => 'To moze potrwac kilka minut — AI tworzy dzielo sztuki...',
    ],

    'sceny' => [
        'scena'            => 'Scena {numer}',
        'model_obrazu'     => 'Model obrazu',
        'model_wideo'      => 'Model wideo',
        'glos'             => 'Glos',
        'odtworz_narracje' => '▶️ Narracja',
        'odtworz_muzyke'   => '🎵 Muzyka',
        'odtworz_wideo'    => '🎬 Wideo',
    ],

    'odtwarzacz' => [
        'tytul'      => 'Odtwarzacz filmu',
        'odtworz'    => '▶️ Odtworz calosc',
        'pauza'      => '⏸️ Pauza',
        'nastepna'   => '⏭️ Nastepna scena',
        'poprzednia' => '⏮️ Poprzednia scena',
        'pelny_ekran' => '🔳 Pelny ekran',
    ],

    'informacje' => [
        'tytul_filmu' => 'Tytul',
        'gatunek'     => 'Gatunek',
        'nastroj'     => 'Nastroj',
        'modele'      => 'Uzyte modele AI',
        'id_projektu' => 'ID projektu',
        'link_snu'    => '🌙 Zobacz ten sen publicznie',
    ],

    'sny' => [
        'tytul_strony'       => 'Sny',
        'opis_strony'        => 'Przeglądaj sny wygenerowane przez AI — każdy sen to wyjątkowe dzieło wyobraźni.',
        'wszystkie_tytul'    => 'Wszystkie Sny',
        'wszystkie_opis'     => 'Sny ze wszystkich języków — odkryj oniryczne światy innych.',
        'filtr_dzien'        => 'Sny z {dzien} {miesiac} {rok}',
        'filtr_miesiac'      => 'Sny z {miesiac} {rok}',
        'filtr_rok'          => 'Sny z roku {rok}',
        'brak_snow'          => 'Brak snów w tym okresie.',
        'brak_snow_jezyk'    => 'Brak snów w tym języku w wybranym okresie.',
        'brak_snow_wszystkie' => 'Brak snów w archiwum.',
        'zobacz_sen'         => 'Zobacz Sen',
        'powrot'             => '← Powrót do snów',
        'odtworz_film'       => '▶ Odtwórz film',
        'strona'             => 'Strona',
        'z'                  => 'z',
        'poprzednia'         => '← Poprzednia',
        'nastepna'           => 'Następna →',
        'wstep'              => 'Wstęp do snu',
        'gatunek'            => 'Gatunek',
        'nastroj'            => 'Nastrój',
        'data_snu'           => 'Data snu',
        'jezyk_snu'          => 'Język oryginału',
        'archiwum'           => 'Archiwum',
        'sen_zapisany'       => '✅ Sen zapisany w archiwum!',
        'sen_link'           => 'Zobacz go tutaj',
        'miesiac_01'         => 'styczeń',
        'miesiac_02'         => 'luty',
        'miesiac_03'         => 'marzec',
        'miesiac_04'         => 'kwiecień',
        'miesiac_05'         => 'maj',
        'miesiac_06'         => 'czerwiec',
        'miesiac_07'         => 'lipiec',
        'miesiac_08'         => 'sierpień',
        'miesiac_09'         => 'wrzesień',
        'miesiac_10'         => 'październik',
        'miesiac_11'         => 'listopad',
        'miesiac_12'         => 'grudzień',
    ],

    'jak_dziala' => [
        'tytul'             => 'Jak to działa?',
        'opis'              => 'Film ze Snu to aplikacja AI, która zamienia opis twojego snu w prawdziwe dzieło filmowe.',
        'krok_1_tytul'      => '1. Opisz swój sen',
        'krok_1_opis'       => 'Wpisz opis snu — im bardziej szczegółowy, tym piękniejszy film. Możesz też nagrać opis głosem.',
        'krok_2_tytul'      => '2. AI tworzy scenariusz',
        'krok_2_opis'       => 'Sztuczna inteligencja analizuje twój sen i tworzy 4-scenowy scenariusz filmowy z tytułem, gatunkiem i nastrojem.',
        'krok_3_tytul'      => '3. Generowanie obrazów',
        'krok_3_opis'       => 'Każda scena otrzymuje unikalny obraz AI — surrealistyczny, kinematograficzny, zgodny z nastrojem snu.',
        'krok_4_tytul'      => '4. Narracja i muzyka',
        'krok_4_opis'       => 'AI nagrywa narrację głosową do każdej sceny oraz komponuje muzykę tła dopasowaną do klimatu.',
        'krok_5_tytul'      => '5. Opcjonalne wideo',
        'krok_5_opis'       => 'Możesz wygenerować animowane klipy wideo dla każdej sceny, które ożywią twój sen.',
        'krok_6_tytul'      => '6. Oglądaj i dziel się',
        'krok_6_opis'       => 'Gotowy film możesz obejrzeć w odtwarzaczu, a sen trafia do publicznego archiwum snów.',
        'technologie_tytul' => 'Technologie',
        'technologie_opis'  => 'Aplikacja korzysta z Pollinations AI — bezpłatnej platformy z dostępem do wielu modeli AI.',
        'faq_tytul'         => 'Często zadawane pytania',
        'faq_1_pytanie'     => 'Czy to jest darmowe?',
        'faq_1_odpowiedz'   => 'Tak! Aplikacja korzysta z bezpłatnych modeli Pollinations AI. Wymagany jest jedynie klucz API.',
        'faq_2_pytanie'     => 'Jak długo trwa generowanie?',
        'faq_2_odpowiedz'   => 'Zazwyczaj 1-3 minuty bez wideo, 5-10 minut z wideo.',
        'faq_3_pytanie'     => 'W jakich językach działa?',
        'faq_3_odpowiedz'   => 'Scenariusz i narracja są generowane w języku wybranym przez użytkownika.',
    ],

    'stopka' => [
        'tekst'       => 'Stworzone z pomoca Pollinations AI',
        'prawa'       => '© {rok} Film ze Snu. Wszystkie prawa zastrzezone.',
        'technologie' => 'Technologie',
    ],

    'bledy' => [
        'brak_opisu'     => 'Wprowadz opis snu.',
        'za_krotki'      => 'Opis snu jest za krotki — minimum 20 znakow.',
        'blad_serwera'   => 'Blad serwera. Sprobuj ponownie pozniej.',
        'blad_api'       => 'Blad komunikacji z AI. Sprawdz klucz API.',
        'brak_mikrofonu' => 'Brak dostepu do mikrofonu.',
        'nie_znaleziono' => 'Nie znaleziono snu.',
        'blad_404'       => 'Strona nie istnieje.',
    ],
];
